### ISSUE TITLE
Model chooses to create docker image by default  when using --repo_path. The docker image does not download using requirement.txt

### ISSUE THREAD

**Issue by samuelmaina** [ersilia-os/eos59rr#1]
Hi @miquelduranfrigola  ,
This is the issue  of building docker image when using the --repo_path arg.The model says that python/conda is not enough  opting to use docker image to create the model. The docker image downloads packages stated in the Docker file but does not download the packages from requirement.txt  that is downloaded from somewhere else. I could add the packages from the requirement.txt manually but I  think there should be a workaround. The docker images created requires 500mb per run and does not cache which is internet intensive. 

```
#9 ERROR: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 2
------
 > [5/8] RUN pip install -r requirements.txt:
#9 1015.3     decode_content=False,
#9 1015.3   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
#9 1015.3     data = self.read(amt=amt, decode_content=decode_content)
#9 1015.3   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 541, in read
#9 1015.3     raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
#9 1015.3   File "/opt/conda/lib/python3.7/contextlib.py", line 130, in __exit__
#9 1015.3     self.gen.throw(type, value, traceback)
#9 1015.3   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 443, in _error_catcher
#9 1015.3     raise ReadTimeoutError(self._pool, None, "Read timed out.")
#9 1015.3 pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.
------
Dockerfile:7
--------------------
   5 |     RUN pip install rdkit
   6 |     RUN wget https://raw.githubusercontent.com/ersilia-os/eos6m4j/main/model/framework/code/bidd-molmap/requirements.txt
   7 | >>> RUN pip install -r requirements.txt
   8 |     RUN pip install h5py==2.10.0
   9 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install -r requirements.txt" did not complete successfully: exit code: 2
18:32:14 | DEBUG    | Running docker
Unable to find image 'ersiliaos/eos59rr:repo' locally
docker: Error response from daemon: pull access denied for ersiliaos/eos59rr, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```
<br/>

- The command  typed: 
       - ersilia -v fetch eos59rr --repo_path 'eos59rr' > eos59rr_local_cli_fetch.log 2>&1
- The whole logs file:
       - [eos59rr_local_cli_fetch.log](https://github.com/ersilia-os/eos59rr/files/11983898/eos59rr_local_cli_fetch.log)

**Comment by miquelduranfrigola** [comment]
Thanks @samuelmaina this is useful.

Are you running this inside docker? If so, which image have you build? What are the specific commands to get to the docker terminal?

**Comment by samuelmaina** [comment]
No, I am not running it in docker, I used the normal `--repo_path`   and Ersilia choose to build the model using an image saying python/conda is not enough. I have docker installed and it's functional.

**Comment by GemmaTuron** [comment]
Hi @samuelmaina 

If you look into the log file, it seems the model fails to fetch simply because your internet connection times out? I don't think this is related to docker or not. It fails while building:
```
#9 963.4 Collecting llvmlite<0.35,>=0.34.0.dev0
#9 963.8   Downloading llvmlite-0.34.0-cp37-cp37m-manylinux2010_x86_64.whl (24.6 MB)
#9 1015.3 ERROR: Exception:
#9 1015.3 Traceback (most recent call last):
#9 1015.3   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 438, in _error_catcher
#9 1015.3     yield
#9 1015.3   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
#9 1015.3     data = self._fp.read(amt) if not fp_closed else b""
#9 1015.3   File "/opt/conda/lib/python3.7/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 62, in read
#9 1015.3     data = self.__fp.read(amt)
#9 1015.3   File "/opt/conda/lib/python3.7/http/client.py", line 457, in read
#9 1015.3     n = self.readinto(b)
#9 1015.3   File "/opt/conda/lib/python3.7/http/client.py", line 501, in readinto
#9 1015.3     n = self.fp.readinto(b)
#9 1015.3   File "/opt/conda/lib/python3.7/socket.py", line 589, in readinto
#9 1015.3     return self._sock.recv_into(b)
#9 1015.3   File "/opt/conda/lib/python3.7/ssl.py", line 1071, in recv_into
#9 1015.3     return self.read(nbytes, buffer)
#9 1015.3   File "/opt/conda/lib/python3.7/ssl.py", line 929, in read
#9 1015.3     return self._sslobj.read(len, buffer)
#9 1015.3 socket.timeout: The read operation timed out
```

**Comment by GemmaTuron** [comment]
I have been able to clone and fetch from repo_path without problems. Indeed it uses Docker:

```
12:26:41 | DEBUG    | Model needs some installs
12:26:41 | DEBUG    | Checking if only python/conda install will be sufficient
12:26:41 | DEBUG    | The python/conda installs may not be sufficient, trying docker
12:26:41 | DEBUG    | Mode: docker
12:26:42 | DEBUG    | BentoML path exists! Removing it: /home/gturon/bentoml/repository/eos59rr
12:26:46 | DEBUG    | Trying to remove path: /home/gturon/bentoml/repository/eos59rr
12:26:46 | DEBUG    | ...successfully
12:26:46 | DEBUG    | Initializing conda packer
12:26:46 | DEBUG    | Packing model with Conda
12:26:46 | DEBUG    | Writing install commands
12:26:46 | DEBUG    | Run commands: ['pip install tmap', 'pip install rdkit', 'wget https://raw.githubusercontent.com/ersilia-os/eos59rr/main/model/framework/code/bidd-molmap/requirements.txt', 'pip install -r requirements.txt', 'pip install h5py==2.10.0']
12:26:46 | DEBUG    | Writing install commands in /home/gturon/eos/dest/eos59rr/model_install_commands.sh
12:26:46 | DEBUG    | Setting up
12:26:46 | DEBUG    | Installs file /home/gturon/eos/dest/eos59rr/model_install_commands.sh
12:26:46 | DEBUG    | Conda environment eos59rr
12:26:50 | DEBUG    | Environment eos59rr does not exist
12:26:54 | INFO     | Cloning base conda environment and adding model dependencies
```

**Comment by GemmaTuron** [comment]
the model testing has also worked so I'll close this as concluded
@miquelduranfrigola we need to update zairachem
